# 测试环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/architecture_pro_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    com.architecturepro: INFO
  file:
    path: ./logs

architecture-pro:
  security:
    swagger-public-enabled: true

vg:
  # 测试环境默认关闭邮件模块，避免误发真实邮件
  lite-email:
    # 是否启用邮件模块
    enabled: false
